CREATE TABLE STUDENT(
	ID INT UNIQUE,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	PHONE INT UNIQUE,
	ORDER_ID INT PRIMARY KEY,
	BOOKING_PRICE DECIMAL(3,2),
	COURSES VARCHAR(20),
	SCOURE DECIMAL(2,1)
);
CREATE TABLE CENTER(
	ID INT UNIQUE,
	CODE INT PRIMARY KEY,
	DATE_FROM TIME,
	DATE_TO TIME,
	COURSE VARCHAR(20),
	PRICE DECIMAL(3,2),
	TEACHER_NAME VARCHAR(20) UNIQUE,
);
CREATE TABLE TEACHER(
	ID INT UNIQUE,
	FIRST_NAME VARCHAR(20) UNIQUE,
	LAST_NAME VARCHAR(20) UNIQUE,
	AGE INT,
	PHONE INT UNIQUE,
	CODE INT UNIQUE,
	SALARY DECIMAL(4,2) NOT NULL,
	COURSE VARCHAR(20),
	FOREIGN KEY (CODE) REFERENCES CENTER(CODE)
);
CREATE TABLE EMPLOYEE(
	ID INT UNIQUE,
	FIRST_NAME VARCHAR(20) UNIQUE,
	LAST_NAME VARCHAR(20) UNIQUE,
	AGE INT,
	PHONE INT UNIQUE,
	CODE INT,
	SALARY DECIMAL(4,2),
	TYPE_WORK VARCHAR(20),
	FOREIGN KEY (CODE) REFERENCES CENTER(CODE)
);

CREATE TABLE ORDERS(
	ID INT UNIQUE,
	TOTAL_PRICE DECIMAL(2,2),
	DATE_ORDER DATETIME,
	BOOKING_CORUSES VARCHAR(20),
	NAME_STUDENT VARCHAR(20),
	FOREIGN KEY (ID) REFERENCES STUDENT(ORDER_ID)
	
);